### ISSUE TITLE
plz add hactoberfest-accepted label to this reposistory. so that it will count in hactoberfest

### ISSUE THREAD

**Issue by virendrasingal** [AkhzarFarhan/HactoberFest-2020#59]
plz add hactoberfest-accepted label to this reposistory. so that it will count in hactoberfest

_Originally posted by @virendrasingal in https://github.com/AkhzarFarhan/HactoberFest-2020/pull/41#issuecomment-712598829_

**Comment by AkhzarFarhan** [comment]
Hi @virendrasingal ,
Thanks for the suggestion.
